#! /bin/sh
#xterm
#sxhkd 2>~/.errdebug > ~/.outdebug &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
# 32
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config history_aware_focus  true
bspc config adaptive raise 	 true

bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop=^7 focus=on
bspc rule -a Slack desktop=^5 focus=on

~/panel/melonpanel 2>/tmp/.errbardebug > /tmp/.outbardebug &
#feh --bg-fill ~/Pictures/light.png
